package com.anrisoftware.groovybash.core.buildins.runbuildin

'''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat, ante quis molestie hendrerit, odio nulla viverra mauris, tincidunt volutpat nisl lorem sed ante. Quisque luctus euismod mauris, ut pulvinar lectus facilisis a. Donec semper cursus nulla vitae cursus. Mauris cursus volutpat ante ut elementum. Donec fringilla urna non sem egestas eu fringilla dolor vestibulum. Vestibulum eu nisl et leo sagittis ultricies non ac sapien. Mauris eu dolor vel magna faucibus dapibus vitae quis sem. Duis scelerisque, orci ut iaculis imperdiet, massa turpis sodales risus, sit amet venenatis nulla sem vel est. Sed luctus velit ut nulla cursus ullamcorper nec ac ante. Donec rhoncus egestas odio. Mauris elementum, nisi rutrum porttitor ullamcorper, nunc erat aliquam lacus, eu lacinia nulla odio id mauris. Ut varius eros condimentum elit mollis condimentum.

Vestibulum quam metus, ornare sed adipiscing quis, congue vel leo. Donec commodo arcu sit amet diam volutpat placerat scelerisque dui fringilla. Suspendisse potenti. Curabitur urna est, mattis sed fringilla sed, dignissim et nulla. Proin interdum arcu at tellus lacinia et pulvinar arcu fermentum. Etiam nisl velit, scelerisque quis dignissim quis, dictum sed urna. Etiam ac tellus velit, nec eleifend odio. Nam est lacus, placerat eget malesuada eu, sagittis a ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Cras dictum, leo ac tincidunt scelerisque, erat quam dapibus nisl, vitae vestibulum mauris nisi in massa. Praesent tristique molestie leo quis egestas. Proin vitae dolor mauris. Vestibulum condimentum, neque non sodales aliquam, sapien diam accumsan orci, et dignissim risus dui eu magna. Aenean vitae mi at turpis cursus faucibus. Etiam viverra, felis eu blandit eleifend, metus dui consectetur purus, non accumsan massa elit vel nisl. Phasellus sodales pulvinar augue ac volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed commodo urna vel justo placerat placerat. Fusce elementum, neque et suscipit sollicitudin, arcu massa euismod mauris, eu volutpat urna augue eleifend lectus. Suspendisse bibendum, velit nec pharetra volutpat, arcu magna mollis lacus, sit amet mollis dui quam ornare leo. Aenean ante mi, commodo quis gravida ac, fermentum non elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas pretium euismod nulla, at pulvinar ipsum cursus sed. Pellentesque fermentum lorem eu ipsum pharetra non viverra libero rutrum. Suspendisse imperdiet faucibus odio, et varius leo mollis sed.

Aenean ornare iaculis velit, suscipit vehicula diam pulvinar at. Fusce vestibulum hendrerit eros, vitae semper justo suscipit quis. Duis enim purus, malesuada id dignissim id, venenatis luctus mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque ultricies pellentesque erat eu interdum. Morbi at tellus vitae velit aliquet egestas. Morbi nec ante nec magna elementum faucibus. Etiam magna quam, convallis dapibus varius nec, aliquam quis mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac tincidunt est.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec pulvinar dictum libero, ac consectetur augue cursus nec. Praesent interdum sodales mauris, in fermentum lorem rhoncus dictum. Sed a malesuada dui. Cras consectetur sapien vitae est tincidunt tincidunt. Phasellus elit lacus, dictum non eleifend id, volutpat vitae orci. Quisque a est eu leo suscipit interdum non non dolor. Integer tristique nisl eu lorem iaculis vitae fringilla est gravida. Quisque ac urna dolor, ut ornare nibh. Etiam lobortis bibendum euismod. Curabitur mattis nulla scelerisque quam sodales a bibendum magna varius. Suspendisse tempus urna non enim dignissim ornare. Aliquam erat volutpat. Praesent eleifend imperdiet pulvinar. Maecenas at nunc magna. Donec hendrerit, libero at laoreet porttitor, diam dui scelerisque lectus, sit amet semper leo ante sed erat.

Sed ac justo ac dolor accumsan tristique in ut dolor. Suspendisse suscipit laoreet placerat. Donec ac metus augue. Nunc non elit nisi, eget dapibus velit. Curabitur sapien metus, facilisis fermentum vulputate id, sagittis et massa. Mauris id neque sed turpis aliquet interdum at eu lacus. Nunc bibendum, diam consequat porttitor varius, arcu ligula euismod nisl, a tristique tortor quam et enim. Morbi consectetur nunc eget diam feugiat malesuada. Curabitur facilisis pellentesque rutrum. Mauris vel mauris sem, ac commodo justo. Maecenas malesuada fringilla diam, nec auctor sapien sollicitudin quis.

Fusce pretium enim non ligula ultricies sodales. Ut ullamcorper semper aliquet. Ut id augue ipsum, quis mattis ligula. Nam quis quam convallis lectus lobortis porttitor. Aliquam erat volutpat. In laoreet congue lorem eu gravida. Nulla nisi turpis, hendrerit et aliquam nec, pretium ut augue. Suspendisse rutrum ultrices nulla nec eleifend.

Suspendisse porttitor ligula eget felis placerat volutpat. In nisi ipsum, ultricies sed feugiat at, condimentum sit amet risus. Donec lacus erat, molestie ut mattis at, luctus sit amet tellus. Sed interdum mi at tellus bibendum venenatis. Donec eu erat luctus mauris sodales pharetra quis volutpat erat. Ut consectetur, augue eu laoreet eleifend, turpis ante tempus augue, sit amet dictum mauris leo vitae dui. Proin nibh nulla, dignissim in egestas vitae, lacinia hendrerit nibh. Aliquam eros ipsum, elementum sit amet ultricies eget, accumsan sed nunc. Mauris suscipit tincidunt ultricies. Sed molestie turpis quis mauris iaculis consequat. Sed euismod nunc id tellus aliquet vestibulum.

Mauris nec ligula nibh. Nunc dignissim porttitor elementum. Donec consectetur condimentum est ut facilisis. Etiam enim eros, eleifend sed porta at, iaculis nec elit. Donec eu mauris nec lectus pharetra dictum id nec nisi. Fusce posuere, mi nec condimentum sodales, libero leo dignissim libero, a cursus leo lorem ut nulla. Suspendisse hendrerit malesuada ligula ut ultricies. Suspendisse nisi lacus, interdum sed mollis et, molestie id tortor. Nam sodales lectus nec augue adipiscing tempor. Phasellus vel elit massa. Curabitur euismod euismod libero, sit amet mattis purus lacinia et. Curabitur lacus nunc, congue ut congue id, hendrerit non massa. Suspendisse porttitor placerat dolor, sodales condimentum metus suscipit et. Fusce tristique metus eget dui lobortis sit amet ultrices sem aliquet.

Maecenas quis dignissim elit. Praesent non nunc non tellus vulputate molestie id non odio. Praesent eget est ac lacus lacinia iaculis. Phasellus porta rhoncus purus, vitae venenatis urna rutrum in. Morbi non ipsum justo. Quisque in odio eu nibh fringilla molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis sollicitudin pulvinar justo, dapibus adipiscing diam pulvinar ac. Etiam bibendum imperdiet massa eget malesuada. Proin viverra ipsum in ante lacinia in mollis leo vulputate. Phasellus fringilla enim eget ligula iaculis pulvinar. In convallis, odio id aliquam faucibus, tortor purus rutrum augue, commodo pretium risus sapien vitae augue. Pellentesque faucibus vehicula sem, dignissim luctus dui iaculis at. Aenean hendrerit fermentum scelerisque. Nunc erat sem, luctus nec egestas sit amet, consectetur eget felis.

Vivamus auctor, urna in aliquam faucibus, est risus ultrices sapien, nec dignissim nunc leo vitae sapien. Donec rutrum nulla id libero rutrum accumsan. Duis laoreet elit at velit sodales quis lobortis leo placerat. Mauris malesuada lacus nec tellus accumsan eu imperdiet leo eleifend. Cras lacinia tincidunt quam at suscipit. Vivamus et ullamcorper tellus. Ut et urna est.

Fusce quam risus, pharetra in imperdiet sit amet, volutpat vitae nibh. In hac habitasse platea dictumst. Suspendisse erat nisl, pharetra sit amet accumsan tempor, egestas sed massa. Sed eleifend lectus et dolor pharetra viverra. Suspendisse tristique tortor at nunc fringilla porta. Quisque quis diam sapien. Ut leo magna, egestas vel bibendum et, pulvinar sit amet elit. Vestibulum in eros nibh. Aenean ac arcu dui, cursus volutpat mauris. Phasellus at rutrum est. Vestibulum a orci porta libero fringilla commodo. Nam sed nibh nec nunc ornare gravida sed tincidunt metus. Sed ac purus nunc. Fusce elementum aliquet justo, id imperdiet neque aliquam quis. Nulla tempor auctor magna in egestas. Fusce vel ante velit.

Sed nisi metus, aliquam eget iaculis et, accumsan id purus. Suspendisse porta orci quis augue fringilla egestas consequat ligula mollis. Nullam sed felis magna. Curabitur erat sapien, congue a viverra nec, tempor vel risus. Vestibulum a libero ligula, sed pulvinar odio. Nullam vel odio magna, at posuere nulla. Morbi tempor tempor nunc id vehicula. Donec laoreet erat eu lacus blandit id imperdiet est sollicitudin.

Aliquam a ipsum dui. Proin sodales, lorem et tincidunt rutrum, nibh risus dictum diam, non commodo leo orci in dui. Phasellus bibendum nulla vehicula quam euismod cursus. Duis bibendum dignissim hendrerit. Nam pulvinar ultrices vestibulum. Cras in interdum nibh. Donec quis nibh vel nunc hendrerit suscipit. Curabitur at nisl non nulla feugiat blandit.

Morbi posuere, arcu a semper eleifend, dolor est porttitor diam, ut adipiscing ipsum lorem sed mi. Donec arcu ligula, porttitor vitae semper ac, luctus nec libero. Mauris dictum, augue at rutrum mollis, nisi ante posuere enim, a hendrerit eros diam sed quam. Duis id facilisis dui. Donec faucibus pharetra vulputate. In odio risus, tempor id mattis vel, pellentesque sed nunc. Donec pretium volutpat massa vel iaculis. Maecenas venenatis mollis tellus, nec tempus massa dignissim eget. Pellentesque tempus bibendum pretium. Duis at elit erat.

Quisque et tortor tellus, sed tempor ligula. Duis sapien risus, facilisis at volutpat vel, mollis ornare ipsum. Proin eu nibh quis ante dictum vehicula vitae ut magna. Sed quam augue, elementum eget ullamcorper id, porttitor eget nulla. Nulla luctus sodales scelerisque. Duis velit tortor, facilisis in pulvinar nec, laoreet at erat. Aenean libero eros, imperdiet id lacinia at, aliquet at purus. Fusce sodales mollis ornare. Fusce eleifend erat et lacus volutpat eu laoreet erat rhoncus. Duis dui dolor, aliquam in elementum sit amet, dapibus ut urna. Nulla consectetur mollis urna, vitae mattis turpis tempus quis.

Etiam porta risus in magna aliquet varius. Quisque imperdiet ligula sed mauris ultrices at egestas ipsum sodales. Duis vel ipsum non dui congue pulvinar at et tellus. Sed leo massa, adipiscing id sagittis ut, porttitor vel velit. Mauris ut aliquet ipsum. Nulla facilisi. Mauris nec massa in dui fermentum tristique a sed quam. Pellentesque et egestas nisl.

Donec non leo sed nisl blandit varius vel quis purus. Pellentesque at quam arcu, vitae dictum nulla. Integer sem purus, interdum quis elementum vel, dignissim in ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum a egestas lorem. Cras sit amet ligula nibh. Etiam quis lorem libero. Curabitur commodo consequat lectus, eget egestas nunc sodales ut. Morbi eget mauris a purus venenatis tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Proin ultricies neque varius massa viverra non dapibus ipsum volutpat. Nam a metus sit amet mi lacinia posuere. Nullam mattis nisi nec massa condimentum a dignissim erat varius. Vivamus egestas, odio nec blandit pharetra, libero erat lobortis nibh, vel condimentum turpis eros non velit. Vestibulum cursus nisl vel tortor egestas convallis. Vestibulum iaculis vehicula risus, in pulvinar dui dictum ut. Maecenas ultrices blandit laoreet. Morbi vehicula neque at sem molestie at varius sem cursus. Duis sollicitudin adipiscing quam, a feugiat lacus dignissim et. In ac eros leo, ac posuere augue. In hac habitasse platea dictumst. Vivamus scelerisque adipiscing viverra. Ut mauris arcu, eleifend at tincidunt sed, commodo sit amet turpis.

Aenean id augue diam, quis mollis est. Duis facilisis, mauris vel interdum aliquet, nunc neque imperdiet sem, sed volutpat erat lectus vitae dui. Vestibulum et metus at lacus varius condimentum a et sapien. Aenean eu lectus diam. Maecenas consectetur blandit venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Proin eget nibh tortor, sed suscipit purus. Pellentesque id vehicula est. Fusce facilisis congue lacus id tincidunt. Donec nisi augue, fermentum at gravida bibendum, facilisis vitae enim. Fusce sit amet semper nisl. Sed elementum, elit non ornare placerat, erat lacus accumsan neque, tristique luctus nisl eros ut ante.

Fusce vehicula nibh at velit molestie sit amet aliquet purus vulputate. Praesent venenatis venenatis dolor, ultricies consequat augue semper eu. Proin nec erat diam, vel dictum nisi. Mauris vel neque sit amet ante dapibus accumsan. Suspendisse bibendum sollicitudin dui non elementum. Fusce eu massa ligula, vitae laoreet nunc. Praesent at libero lectus. Mauris in ante dui, ut gravida velit. Maecenas vitae lorem justo, a tristique mi. Suspendisse purus orci, semper eu feugiat non, pretium vel orci. Nullam congue elit ut ipsum ullamcorper dictum. Aenean imperdiet egestas elit, a congue arcu tempor vitae. Cras dignissim tellus at massa iaculis porta. Donec lacinia, orci rutrum ultricies sagittis, eros turpis ornare tortor, et placerat nisi urna sit amet metus. Suspendisse potenti.

Nulla facilisi. In tempor est et diam volutpat sagittis. Quisque et justo tortor. Nullam eget facilisis enim. Nam et ipsum eget mauris euismod pharetra. Morbi et velit a neque semper laoreet. Donec ullamcorper mattis scelerisque. Sed dapibus ipsum non lectus porta ut blandit odio consectetur. Aliquam erat volutpat. Cras sagittis nisl sed libero facilisis dapibus. In tempor euismod tellus, sed porta est blandit non. Quisque nibh nisl, congue eu vehicula vel, molestie sit amet turpis. Vivamus neque libero, tincidunt vel tempus a, viverra et nibh. Mauris rutrum neque mattis orci vulputate vitae rhoncus velit malesuada. Mauris in magna non eros malesuada dapibus vitae eget dui.

Morbi eget nisl nec mauris tempus suscipit. Vestibulum gravida molestie aliquet. Morbi sagittis leo in odio luctus sed molestie velit adipiscing. Nullam mattis nunc egestas magna sodales blandit. Curabitur viverra aliquam magna, bibendum pellentesque neque facilisis eu. Pellentesque posuere risus non tellus interdum vel posuere quam mollis. Vestibulum dictum velit a nulla tempus consequat. Praesent eleifend aliquam vehicula. Quisque posuere bibendum convallis. Aenean ut tortor sed justo dictum tincidunt. Nullam congue ante sit amet felis posuere fermentum. Duis ornare imperdiet scelerisque. Nam eget tortor vulputate massa pulvinar interdum nec sit amet quam. Sed volutpat augue viverra massa malesuada aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc enim dolor, accumsan eget lobortis nec, tincidunt id mi.

Nunc sodales metus nec neque consectetur volutpat. Curabitur ultricies, ante ac eleifend ultrices, tellus augue egestas velit, sed consequat tortor nisl semper nibh. Fusce lectus lectus, fringilla at rutrum non, tempus at sem. Nullam rhoncus laoreet velit sed adipiscing. Mauris viverra nisi at nunc accumsan at pharetra diam malesuada. Aliquam sed dui velit. Duis id justo sit amet nisl semper pulvinar. Praesent vel enim vitae ligula hendrerit egestas non ut erat. Mauris ac lectus eu orci cursus scelerisque. Suspendisse accumsan, tellus vel hendrerit molestie, purus quam lacinia nisi, eu aliquet sapien urna sit amet arcu.

Quisque sollicitudin gravida neque, nec hendrerit lacus blandit eget. Nunc vestibulum lacinia justo. Sed id nisi quis purus venenatis sagittis. Sed vehicula odio sit amet odio laoreet ut tempus mauris ultrices. Morbi vel nulla vel dui ullamcorper fringilla et ut diam. Vestibulum pellentesque lectus quis ipsum imperdiet id condimentum justo gravida. Sed ac orci quis diam pharetra luctus. Nullam nec enim diam, sed pulvinar diam.
'''
